version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:7.10

jobs:
  setup:
    <<: *defaults
    steps:
      - checkout:
          path: ~/repo
      - attach_workspace:
          at: ~/repo
      - run:
          name: NPM Dependencies
          command: yarn install
      - persist_to_workspace:
          root: .
          paths:
           - .

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Build Library
          command: yarn build

  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo/dist
      - run:
          name: Publish on NPM
          command: npm publish

workflows:
  version: 2
  setup_build_publish:
    jobs:
      - setup
      - build:
          requires:
            - setup
      - publish:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*/
